# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm run cy:run
  displayName: 'Run testes on Electron'
  continueOnError: true
  
- script: npm run cy:chrome
  displayName: 'Run testes on Chrome'
  continueOnError: true
